---
title: "Broken Stick Model for Irregular Longitudinal Data"
author: "Stef van Buuren"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Broken Stick Model for Irregular Longitudinal Data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
bibliography: bibliography.bib
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r setup, include=FALSE}
require("brokenstick")
require("dplyr")
require("tidyr")
require("ggplot2")
require("lattice")

old <- options(digits = 2)
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, fig.height = 7, fig.width = 7, out.width="100%", dev = "png")

colors <- mice::mdc(1:6)
knitr::knit_hooks$set(set.theme = function(before, options, envir) {
  if (before) 
    lattice::trellis.par.set(list(
      strip.background = list(col = "grey95"),
      superpose.symbol = list(col = colors[1:2]),
      superpose.line = list(col = colors[1:2]),
      plot.symbol = list(col = colors[1:2])))
})
# knitr::knit_hooks$set(set.palette = function(before, options, envir) {
#   if (before) {
#     opal <- palette(colors)
#     opar <- par(cex.main = 1.0)
#   }
# })
```

```{r, child='jss_txt.Rmd'}
```
