---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## What is the broken stick model?

The *broken stick model* describes a set of individual curves by a linear mixed model using second-order linear B-splines. The model can be used to

- smooth growth curves by a series of connected straight lines;
- align irregularly observed curves to a common age grid;
- create synthetic curves at a user-specified set of break ages;
- estimate the time-to-time correlation matrix;
- predict future observations.

The user specifies a set of break ages at which the straight lines connect. Each individual obtains an estimate at each break age, so the set of estimates of the individual form a smoothed version of the observed trajectory. 

## What are the main model assumptions?

The main assumptions of the broken stick model are: 

- The development between the break ages follows a straight line;
- Broken stick estimates follow a common multivariate normal distribution;

In order to conform to the assumption of multivariate normality, the user may fit the broken stick model on suitably transformed data that yield the standard normal ($Z$) scale. 

## Why should I want to use the broken stick model?

Three unique features of the broken stick model are:

- *Modular*: Issues related to nonlinearities of the growth curves in the observed scale can be treated separately, i.e., outside the broken stick model;
- *Local*: A given data point will contribute only to the estimates corresponding to the closest break ages;
- *Exportable*: The broken stick model can be exported and reused for prediction for new data in alternative computing environments.

## What is in the package?

The `brokenstick` package contains functions to fit, predict and plot data. See the [reference page](https://growthcharts.org/brokenstick/reference/) for an overview.

### Acknowledgment

This work was supported by the Bill & Melinda Gates Foundation. The contents are the sole responsibility of the authors and may not necessarily represent the official views of the Bill & Melinda Gates Foundation or other agencies that may have supported the primary data studies used in the present study. 


