---
title: "Introduction"
author: "Stef van Buuren"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

The *broken stick model* describes a set of individual curves by a linear mixed model using first order linear B-splines. The model can be used

- to smooth growth curves by a series of connected straight lines;
- to align irregularly observed curves to a common age grid;
- to create synthetic curves at a set of break ages;
- to estimate the time-to-time correlation matrix;
- to predict future observations.

The user specifies a set of break ages at which the straight lines connect. Each individual obtains an estimate at each break age, so the set of estimates of the individual form a smoothed version of the observed trajectory. 

The main assumptions of the broken stick model are: 

- The development between the break ages follows a straight line, and is generally not of particular interest;
- The set of individual estimates follow a common multivariate normal distribution;

In order to conform to the assumption of multivariate normality, the broken stick model is fitted on suitably transformed data in the standard normal ($Z$) scale. Unique feature of the broken stick model are:

- *Modular*: Issues related to nonlinearities of the growth curves in the observed scale can be treated separately, i.e., outside the broken stick model;
- *Local*: A given data point will contribute only to the estimates corresponding to the closest break ages;
- *Exportable*: The broken stick model can be exported and reused for prediction for new data in alternative computing environments.

The `brokenstick` package contains functions for fitting the broken stick model to data, for exporting the parameters of the model for independent use outside this package, and for predicting broken stick curves for new data.

# Main functions

The main functions in the `brokenstick` package are:

Function name        | Description
---------------------|---------------------------------
`make.basis()`         | Create linear splines basis
`fit.brokenstick()`    | Fit a broken stick model to irregular data
`EB()`                 | Empirical Bayes estimation of the random effects
`predictbs()`          | Predict growth curve by the broken stick model
`export.brokenstick()` | Export the estimates of a fitted `lmer()` model object

# Exporatory analysis

```{R}
library(brokenstick)
data <- smocc.hgtwgt
head(data)
```

Plots of the first the height trajectories of two children can be made with the \pkg{lattice} function \code{xyplot()}, as follows:

```{R fig.width = 7}
library(lattice)
xyplot(hgt ~ age | as.factor(id), data = data, 
	   subset = id %in% c(10001, 10005), 
	   type = "b", pch = 19, as.table = TRUE)
```

The plots gain more resolution when the Standard Deviation Scores (SDS) (or $Z$-values) are plotted. The column \code{hgt.z} contains the $Z$-scores of height relative to the WHO standard.

```{R fig.width = 7}
xyplot(hgt.z ~ age | as.factor(id), data = data, 
	   subset = id %in% c(10001, 10005), 
	   type = "b", pch = 19, as.table = TRUE,
	   panel = function(...) {
	   	panel.refline(h = c(-2, 0, 2))
	   	panel.xyplot(...)
	   }
)
```


# Broken stick model with two lines

The *broken stick model* assume that each trajectory can be described by a series of straight, connected lines. Let us first do a rough approximation, and specify that we may only use two lines. Both span a period of one year, and connect exactly at the age of 1 year. 

```{R}
X <- make.basis(x = data$age, knots = 0:2)
head(data.frame(age = data$age, X))
```

The \code{make.basis()} functions takes a vector of *break ages*, here chosen as 0, 1 and 2 years. Each age is coded into two columns as a function of how close it is to the break age. This type of coding is known as the linear B-spline basis of degree 1. The function \code{make.basis()} calculates it by the built-in function \code{bs()} from the \pkg{splines} package.

The broken stick model is fitted to the data of all children as follows:

```{R}
fit2lines <- fit.brokenstick(z = data$hgt.z, 
							 age = data$age,
							 id = data$id,
							 knots = 0:2)
class(fit2lines)
attr(fit2lines, "knots")
```

*Specification*: The \code{knots} arguments specifies that the break ages are birth, 1 year and 2 years, respectively. The broken stick model effectively replaces the intercept by the random effects \code{x0}, \code{x1}, \code{x2} and \code{x3}. The random effects correspond to the break ages of 0, 1, 2 and 3 years, respectively. The break age of 3 years is specified for technical reason as a \code{Boundary.knot}, since the B-splines must encompass the entire age range in the data, but has no useful interpretation. No intercept is needed since every row in \code{X} adds up to one.

```{R}
fit2lines
```

*Interpretation*: The fixed effects correspond to the mean of population of children in the data. At birth, the children are on average 0.1 SD taller than the WHO standard. At the ages of 1 and 2 years, these estimates rise to 0.38 SD and 0.52 SD, respectively. This a not surprising. The Dutch are among the tallest in the world, and we know that at the age of 2 years approximately 50% of the final height has been achieved. The estimate of 0.96 at three years is based on extreme extrapolation, and should be disregarded.

The column labeled \code{Std.Dev.} contains the standard deviations of the random effects. These numbers are expected to be around 1, since - under the assumption that the WHO standard appropriately describes this population - the dependent variable follow a standard normal distribution with zero mean and standard deviation equal to one. The \code{cor} component of the output lists the correlations between the time point. Thus, the correlation between birth length and length at 2 years is about 0.58. 

Finally, the residual (0.49) is the standard deviation of the residual of the model. 

The proportion of explained variance of outcome by the model is:

```{R}
var(fitted(fit2lines)) / var(data$hgt.z)
```

# Plotting the broken stick estimates



# Exporting the broken stick model

```{R}
# export the broken stick models
export.hgt <- export.brokenstick(fit2lines)
export.hgt
```


# Predictions on new data


# Open issues




