---
title: "Knot placement"
author: "Stef van Buuren"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Knot placement}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective

bla bla

## Knot placement strategies

If we want to predict at specific ages, then specify knots at those ages. In general, keep the number of knots low, for speed and simplicity. The broken stick model is sensitive to the location of the knots. Evidently, using more knots can improve the fit to the data. However, adding an excessive number of knots will substantially increase calculation time, and create solutions that are unstable. 

The `boundary` argument should be specified with some care. Specify the first break point `knot[1]` equal to `Boundary.knots[1]` and equal to the minumum age (otherwise unpredictable things occur). For technical reasons, `Boundary.knots[2]` should be equal to or larger than the maximum age in the data. The broken stick estimate at this knot has no useful interpretation.


## Automatic knot placement 

bla bla

## Advice

Limit the number of knots to the (average) number of data points per person. The knots can be added at the scheduled visits, which is a reasonable strategy for obtaining good predictions since there are generally many observations in the neighourbood of the scheduled ages. 

One can always obtain more precise predictions at any age.

Bad knot placement: placing knots at ages where the data are very sparse (e.g. exactly in-between visits) may result in bad predictions and should be avoided.

