---
title: "Getting started"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Overview

The *broken stick model* describes a set of individual curves by a linear mixed model using first order linear B-splines. The model can be used to

- smooth growth curves by a series of connected straight lines;
- align irregularly observed curves to a common age grid;
- create synthetic curves at a user-specified set of break ages;
- estimate the time-to-time correlation matrix;
- predict future observations.

The user specifies a set of break ages at which the straight lines connect. Each individual obtains an estimate at each break age, so the set of estimates of the individual form a smoothed version of the observed trajectory. 

The main assumptions of the broken stick model are: 

- The development between the break ages follows a straight line;
- Broken stick estimates follow a common multivariate normal distribution;

In order to conform to the assumption of multivariate normality, the user may fit the broken stick model on suitably transformed data that yield the standard normal (Z) scale. Unique feature of the broken stick model are:

- *Modular*: Issues related to nonlinearities of the growth curves in the observed scale can be treated separately, i.e., outside the broken stick model;
- *Local*: A given data point will contribute only to the estimates corresponding to the closest break ages;
- *Exportable*: The broken stick model can be exported and reused for prediction for new data in alternative computing environments.

The `brokenstick` package contains functions for

- Fitting the broken stick model to data, 
- Predicting broken stick estimates for new data.
- Exporting the parameters of the model for independent use outside this package.
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 7, fig.height = 3.5)
```

## Main functions

The main functions in the `brokenstick` package are:

Function name        | Description
---------------------|---------------------------------
`brokenstick()`      | Fit a broken stick model to irregular data
`predict()`          | Predict broken stick estimates for new growth data
`export()`           | Export broken stick model parameters 

## Further reading

A [vignette with a simple example](example.html) is available as well. Additional details on model fitting and prediction are given in the [vignette for prediction](prediction.html).
