---
title: "Knot placement"
author: "Stef van Buuren"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Knot placement}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective

The broken stick model is sensitive to the location of the knots. A knot is the age at which two lines connect. The choice of the knots across the age range has a large influence on the quality and interpretability of the solution, so some care is needed in setting appropriate locations. This vignette discusses knot placement.

## Knot placement strategies

By default, the `brokenstick()` function relies on the `pretty()` base function. More often than not, this can result in suboptimal knot placement that is not adequate for the problem at hand.

Here are some suggestions for knot placement:

1. If you want to predict at specific ages, then specify knots at those ages. For example, if the scientific interest includes prediction at ages of 1 year and 2 years, then included these ages as knots. 
2. Keep the number of knots low, for speed and simplicity, but try to model nonlinearities in the data by adding additional knots.
3. Do not place knots in sparsely filled areas of the data, e.g. not in-between two visits. Doing so may result in erratic joins.
4. If possible, set a knot at each scheduled visit. This is a good strategy for obtaining good predictions at exactly the scheduled age as  there are generally many observations in the neighourbood of scheduled ages.
5. Knots are the same for all individuals in the data.
6. Specify the first break point `knots[1]` equal to `boundary[1]`, and equal to the minumum age. The solution is uninterpretable if `knots[1]` and `boundary[1]` differ.
7. Order knots.
8. The highest age in `knots` should correspond to the highest age of scientific interest. Boundary knot `boundary[2]` should set larger than this value (e.g. equal to the the maximum age in the data). The broken stick estimates at this knot have no useful interpretation.
9. The knots used in a fitted brokenstick model can be extracted by the `get_knots()` function.
10. Having many knots (e.g. > 10) can improve the fit to the data. However, a large number of knots will substantially increase calculation time, and result in solutions that are unstable.
11. Limit the number of knots to the (average) number of data points per person. 
