---
title: "Model formulation"
author: "Stef van Buuren"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model formulation}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

This vignette provides the formal definition and interpretation of the broken stick model.

## Notation

We adopt the notation of @fitzmaurice2011. Let $Y_{ij}$ denote the response variable for the $i^{\rm th}$ subject on the $j^{\rm th}$ measurement occasion at time $t_{ij}$. Data are collected in a sample of $N$ persons $i=1,\dots,N$. Let repeated measurements for the $i^{\rm th}$ subject be grouped as 
\[ Y_i = \left( \begin{array} {l} Y_{i1} \\ Y_{i2} \\ \vdots \\ Y_{in_i} \end{array} \right), \quad i = 1, \dots, N.\]
If the measures have been observed at a common same set of occasions, then we could drop the index $i$ in $t_{ij}$ since $t_{ij} = t_j$ for all $i = 1, \dots, N$. Here we will focus on the case that $t_{ij}$ varies over $i$. 

In addition, let use define the $n_i \times p$ matrices
\[ X_i = \left( \begin{array} {llll} 
 X_{i11} & X_{i12} & \cdots & X_{i1p} \\
 X_{i21} & X_{i22} & \cdots & X_{i2p} \\
 \vdots  & \vdots  & \ddots & \vdots  \\
 X_{in_i1} & X_{in_i2} & \cdots & X_{in_ip}
\end{array} \right), \quad i = 1, \dots, N,\]
so that the rows of $X_i$ contain $p$ covariates associated with the responses at $n_i$ measurement occasions. The columns may be time-varying covariates. If a certain covariate is fixed in time (e.g. sex, treatment, education), then all within the corresponding column in $X_i$ are identical.

## Broken stick model

The broken stick model avoids modeling observation times $t_{ij}$ directly by representing each $t_{ij}$ as its relative position within a time interval. For example, suppose $t_{ij} = 0.6$ years and that the time interval is given by 0.5-1.0 years. The position relative to the left break age is $x_{\rm left} = (1.0-0.6)/(1.0-0.5) = 0.8$, whereas relative to the right break age is $x_{\rm right} = (0.6-0.5)/(1.0-0.5) = 0.2$. In order to fit the broken stick model, we need to replace time point $t_{ij} = 0.6$ by two values: 0.8 (for break age 0.5), and 0.2 (for break age 1.0). Note that both values add up to 1. Coding time in this way simplifies modeling continuous time by a set of discrete break ages.

More specifically, let $t_{ij}$ be coded by a second order (linear) B-spline using $k$ internal knots $\kappa$ placed at $k+1$ ordered ages
$$
\kappa_0 = \kappa_1 < \dots < \kappa_k < \kappa_{k+1}
$$
The internal knots $\kappa_1, \dots, \kappa_k$ correspond to the set of ages for which we obtain broken stick estimates, and it could be specified by the user. The left boundary knot $\kappa_0 = \kappa_1$ is conveniently set to the minimum age $\min(t_{ij})$ in the data, whereas the right hand boundary knot $\kappa_{k+1} \geq \max(t_{ij})$. 

The second order B-spline [@deboor1978 pp. 32],
$$
H_s(t) = \left\{ \begin{array} {l@{\quad,\quad}l}
(t-\kappa_{s-1})/(\kappa_s - \kappa_{s-1}) & \kappa_{s-1} < t \leq \kappa_s,\\
(\kappa_{s+1}-t)/(\kappa_{s+1} - \kappa_s) & \kappa_s \leq t < \kappa_{s+1},\\
0 & {\rm otherwise.}
\end{array} \right. 
$$
is applied to $t_{ij}$ to obtain $(k+1)$ transformed variables $x_{is} = t_{ij}$ with $s = 1,\dots,k+1$. These variables can conveniently be grouped into the $n_i \times (k+1)$ matrix of covariates $X_i = (x_{i1}, \dots, x_{ik}, x_{i(k+1)})$. Each row in $X_i$ has only one or two non-zero elements, which sum to 1.

Using this $X_i$, the broken stick model is a special case (with $Z_i = X_i$) of the two-stage random-effects model [@laird1982]

$$
Y_i = X_i\beta + X_ib_i + \epsilon_i
$$

where the $k+1$ column vector $\beta$ contains $k+1$ fixed effect coefficients common to all persons, where the $k+1$ column vector $b_i$ accomodates for $k+1$ subject-specific random parameters, and where the $n_i$ column vector $\epsilon_i$ holds subject-specific residuals. 

In order to complete the model specification, we assume that the residuals are identically and independently distributed as $\epsilon_i \sim N(0,\sigma^2 I(n_i))$, where $\sigma^2$ is a common variance parameter, and where $I(n_i)$ is the identity matrix of order $n_i$. Thus, the equation represents population parameters (fixed effects), individual effects (random effects), and an amount of within-person dispersion that is the same for all persons.

At the person level, we assume $b_i \sim N(0, \Omega)$, i.e., the random coefficients of the subjects have a multivariate normal distribution with zero mean and a $(k+1) \times (k+1)$ covariance matrix $\Omega$. In addition, we assume that the covariance between $b_i$ and $\epsilon_i$ is zero.

In summary, given the knot specification and the choice of the response scale, the parameters of the broken stick model are:

- $\beta$, a vector of $k + 1$ fixed parameters;
- $\Omega$, a $(k+1) \times (k+1)$ covariance matrix of the random effects;
- $\sigma^2$, the within-person error variance.

The total number of parameters for a solution with $k$ internal knots is thus equal to $(k^2 + 5k + 6)/2$. For example, a model of $k = 3$ knots (i.e. with two connected lines) has 15 parameters, a model with $k = 4$ has 21 parameters, and a model with $k = 10$ break ages has 78 parameters. 

## Interpretation

Interpretation of the broken stick model is as follows. The sum $\gamma_{is} = \beta_s + b_{is}$ is the *conditional* (or subject-specific) mean of $Y_i$ at age $\kappa_s$, $s = 1,\dots, k$. The set of $\gamma_{is}$ parameters describes the mean response profile for any individual as $k-1$ lines that connect at the $k$ coordinates $(\kappa_k, \gamma_{is})$. 

The model effectively represents the $n_i$ measurements of subject $i$ by $k$ new points. The analysis of the $k$ data points at ages $\kappa$ is generally easier than the analysis of $n_i$ values when $t_{ij}$ differs across persons. 

If $n_i >> k$ then the broken stick model provides a parsimonious representation of the measurements. Reversely, if $n_i << k$ then the model infers plausible values for subject $i$ by building strength across persons. The major advantage of the broken stick model is that it converts $n_i$ irregularly observed measurements into a new set of $k$ values $\gamma_{is}$ at common ages $\kappa_1, ..., \kappa_k$, $s = 1,\dots, k$.

Since each row in $X_i$ sums to unity, the broken stick model does not have an intercept term. The linear B-spline coding effectively replaces the conventional random intercept term by $k$ *local intercepts*, one at each break age. The local intercept summarizes the information available in the adjacent left and right age intervals, and ignores any information beyond the adjacent knots. The broken stick estimates are primarily local estimates. Data beyond the adjacent age intervals influence broken stick estimates only through the subject-level part of the model.

