---
title: "Try out kr sampler"
author: "Stef van Buuren"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
%\VignetteIndexEntry{kr sampler}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  ---
  
  ```{r setup, include = FALSE}
  knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
  )
  ```
  
  
  ```{r setup}
  library(brokenstick)
```


```{r setup2}
data <- brokenstick::smocc_200
fits <- with(data, brokenstick(y = hgt.z, x = age, 
                               subjid = subjid, 
                               knots = 1:2,
                               boundary = c(0, 3)))
data2 <- fits@frame
attr(data2, "terms") <- NULL
attr(data2, "na.action") <- NULL
attr(data2, "formula") <- NULL

# library(micemd) - does not work
#fit3 <- mice.impute.2l.2stage.norm(y = data2$y, 
#                                   ry = !is.na(data2$y),
#                                   x = data2[, -1],
#                                   type = c(rep(2, 4), -2),
#                                   method_est = "mm")

fit3 <- kr(y = data2$y,
           ry = !is.na(data2$y),
           x = data2[, -1],
           type = c(rep(2, 4), -2),
           intercept = FALSE)


# lmer
fit0 <- with(data, brokenstick(y = hgt.z, x = age, 
                               subjid = subjid, 
                               knots = round(c(0, 1, 2, 3, 6, 9, 12, 15, 18, 24) / 12, 4),
                               boundary = c(0, 3)))
data2 <- fit_200@frame
exp0 <- export(fit0)

```


```{r}
fit1 <- kr(y = data2$y, 
           ry = !is.na(data2$y), 
           x = data2[, -1], 
           type = c(rep(2, 11), -2),
           intercept = FALSE)
exp1 <- list(
  class = NA,
  beta = fit1$mu,
  omega = solve(fit1$inv.psi),
  sigma2 = mean(1/fit1$inv.sigma2),
  sigma2j = 1/fit1$inv.sigma2,
  knots = NA,
  boundary = NA,
  degree = NA
)

fit2 <- kr(y = data2$y, 
           ry = !is.na(data2$y), 
           x = data2[, c("x1", "x2", "x3", "x4", "subjid")], 
           type = c(2, 2, 2, 2, -2),
           intercept = FALSE)
```

```{r}
z0 <- predict(fit0, at = "knots", output = "broad")
z1 <- fit1$bees
z2 <- fit2$bees
zs <- (z1 + z2) / 2

plot(z0[, 6], z1[, 6]); abline(0, 1)
plot(z0[, 1], z2[, 1]); abline(0, 1)
plot(z1[, 1], z2[, 1]); abline(0, 1)

plot(z0[, 1], zs[, 1]); abline(0, 1)
```

```{r}
library(micemd)
fit3 <- mice.impute.2l.2stage.norm(y = data2$y, 
                                   ry = !is.na(data2$y), 
                                   x = data2[, -1], 
                                   type = c(rep(2, 11), -2),
                                   method_est = "mm")

```

