# new_brokenstick <- function(data = NULL,
#                             formula = NULL,
#                             names = list(x = character(),
#                                          y = character(),
#                                          z = character()),
#                             knots = numeric(0),
#                             boundary = numeric(0),
#                             degree = 1L,
#                             model = NULL,
#                             beta = numeric(0),
#                             omega = numeric(0),
#                             sigma2j = numeric(0),
#                             sigma2 = numeric(0),
#                             imp = numeric(0),
#                             blueprint = hardhat::default_xy_blueprint()) {
#   hardhat::new_model(data = data,
#                      formula = formula,
#                      names = names,
#                      knots = knots,
#                      boundary = boundary,
#                      degree = degree,
#                      model = model,
#                      beta = beta,
#                      omega = omega,
#                      sigma2j = sigma2j,
#                      sigma2 = sigma2,
#                      imp = imp,
#                      blueprint = blueprint,
#                      class = "brokenstick")
# }
new_brokenstick <- function(data = NULL,
                            npred = NULL,
                            nout = NULL,
                            blueprint = hardhat::default_xy_blueprint())
{
  hardhat::new_model(data = data,
                     npred = npred,
                     nout = nout,
                     blueprint = blueprint,
                     class = "brokenstick")
}
