new_brokenstick <- function(data = NULL,
                            names = list(x = character(),
                                         y = character(),
                                         z = character()),
                            knots = numeric(0),
                            boundary = numeric(0),
                            degree = 1L,
                            model = NULL,
                            beta = numeric(0),
                            omega = numeric(0),
                            sigma2j = numeric(0),
                            sigma2 = numeric(0),
                            draws = numeric(0),
                            blueprint = NULL) {
  hardhat::new_model(data = data,
                     names = names,
                     knots = knots,
                     boundary = boundary,
                     degree = degree,
                     model = model,
                     beta = beta,
                     omega = omega,
                     sigma2j = sigma2j,
                     sigma2 = sigma2,
                     draws = draws,
                     blueprint = blueprint,
                     class = "brokenstick")
}
