#' Set controls to steer calculations
#'
#' @param method Either `"kr"` (for the Kasim-Raudenbush sampler)
#' or `"lmer"` (for [lme4::lmer()]).
#' @param lmer A list generated by [lme4::lmerControl]. The default
#' is set to `lmerControl(check.nobs.vs.nRE = "warning")`, which turn
#' fatal errors with respect the number of parameters into warnings. Use
#' `lmerControl(check.nobs.vs.nRE = "ignore")` to silence `lmer()`.
#' @param kr A list with the following components:
#'
#'    * `runin`: Number of run-in iterations
#'    * `ndraw`: Number of parameter draws
#'    * `par_skip`: Number of iterations to next parameter draw
#'    * `imp_skip`: Number of iterations to next outcome draw
#'
#' @param na.action The function to call for the `na.action` argument.
#' The default is `na.exclude`.
#'
#' @export
control_brokenstick <-
  function(method = c("lmer", "kr"),
           lmer = lmerControl(check.nobs.vs.nRE = "warning"),
           kr = list(runin = 100L, ndraw = 200L,
                     par_skip = 1L, imp_skip = Inf),
           na.action = na.exclude) {
    method <- match.arg(method)
    list(method = method,
         lmer = lmer,
         kr = kr,
         na.action = na.action)
  }
