#' Set controls to steer calculations
#'
#' @param method String indicating estimation method: `"kr"` or `"lmer"`
#' @param kr A list generated by [control_kr].
#' @param lmer A list generated by [lme4::lmerControl]. The default
#' is set to `lmerControl(check.nobs.vs.nRE = "warning")`, which turns
#' fatal errors with respect the number of parameters into warnings. Use
#' `lmerControl(check.nobs.vs.nRE = "ignore")` to silence `lmer()`.
#'
#' @export
set_control <- function(method = c("kr", "lmer"),
                        kr = control_kr(),
                        lmer = lmerControl(check.nobs.vs.nRE = "warning")) {
  method <- match.arg(method)
  if (method == "kr") {
    return(kr)
  }
  if (method == "lmer") {
    return(lmer)
  }
  return(NULL)
}

#' Set controls for Kasim-Raudenbush sampler
#' @param n        Integer. Number of samples from posterior. Default:  `n = 200`.
#' @param m        Integer. Number of multiple imputations. Default: `m = 0`.
#' @param start    Integer. The iteration number of the first observation
#' @param thin     Integer. The thinning interval between consecutive observations
#' @param cormodel String indicating the correlation model:
#'                 `"none"` (default), `"argyle"` or `"cole"`
#' @return         A list with five components. The function calculates parameters
#'                 `end` (the iteration number of the last iteration) and
#'                 `thin_imp` (thinning factor for multiple imputations) from the
#'                 other inputs.
#' @export
control_kr <- function(n = 200L,
                       m = 0L,
                       start = 100L,
                       thin = 1L,
                       cormodel = c("none", "argyle", "cole")) {
  cormodel <- match.arg(cormodel)

  end <- start + n * thin
  if (m > n) {
    stop("Number of imputations (m = ", m, ") exceeds number of parameter draws (n = ", n, ").")
  }
  thin_imp <- ifelse(m, as.integer((end - start) / m), Inf)

  list(
    n = n,
    m = m,
    start = start,
    end = end,
    thin = thin,
    thin_imp = thin_imp,
    cormodel = cormodel
  )
}
