#' Set controls to steer calculations
#'
#' @param method String indicating estimation method: `"kr"` or `"lmer"`
#' @param kr A list generated by [control_kr].
#' @param lmer A list generated by [lme4::lmerControl]. The default
#' is set to `lmerControl(check.nobs.vs.nRE = "warning")`, which turns
#' fatal errors with respect the number of parameters into warnings. Use
#' `lmerControl(check.nobs.vs.nRE = "ignore")` to silence `lmer()`.
#'
#' @export
set_control <- function(method = c("kr", "lmer"),
                        kr = control_kr(),
                        lmer = lmerControl(check.nobs.vs.nRE = "warning")) {
  method <- match.arg(method)
  if (method == "kr") {
    return(kr)
  }
  if (method == "lmer") {
    return(lmer)
  }
  return(NULL)
}

#' Set controls for Kasim-Raudenbush sampler
#'
#' @param cormodel String indicating the correlation model:
#'                 `"none"` (default), `"argyle"` or `"cole"`
#' @param m        Integer. Number of multiple imputations. The default `m = 0L`.
#' @param start    Integer. The iteration number of the first observation
#' @param end      Integer. The iteration number of the last observation
#' @param thin     Integer. The thinning interval between consecutive observations
#' @return         A list with five components
#' @export
control_kr <- function(cormodel = c("none", "argyle", "cole"),
                       m = 0L,
                       start = 101L,
                       end = 300L,
                       thin = 1L) {
  cormodel <- match.arg(cormodel)
  n <- trunc((end - start + 1L) / thin)
  # browser()
  if (m > n) {
    stop("Number of imputations (m = ", m, ") exceeds number of draws: ", n, ".")
  }
  if (m > 0L && n %% m != 0L) {
    stop("Number of imputations (m = ", m, ") not a divisor of the number of draws: ", n, ".")
  }
  thin_imp <- ifelse(m, as.integer(n / m), Inf)

  list(
    cormodel = cormodel,
    m = m,
    n = n,
    start = start,
    end = end,
    thin = thin,
    thin_imp = thin_imp
  )
}
